### ISSUE TITLE
Sync Disabled Extensions

### ISSUE THREAD

**Issue by ianrohde** [nonoroazoro/vscode-syncing#93] opened 2022-08-18 16:20 UTC
Would it be difficult to add syncing of disabled extensions? I enable/disable extensions based on the project/workspace, so depending on which workspace I'm in, I get varied results when syncing.

**Comment by nonoroazoro** [comment] 2022-09-22 07:12
Duplicate of https://github.com/nonoroazoro/vscode-syncing/issues/17

**Closed by nonoroazoro** 2022-09-22 07:12 UTC
