### ISSUE TITLE
Downloading some packages causes the extension to hang

### ISSUE THREAD

**Issue by silver-mx** [nonoroazoro/vscode-syncing#22] opened 2017-12-27 12:03 UTC
## Specifications

Syncing version 1.5.1.

I am using linux mint 17.3 and sometimes when syncing (downloading) some specific extensions, I observe that this extension just keep working but does not complete the download process, so it cannot continue to sync the next extension. 

I have tested syncing my packages in another windows machine, and it worked fine, so I am not sure this is an error (maybe an issue in my machine?). Still I see that I can reproduce the problem every time I download my settings in my linux machine, and always with the extensions listed below.

I can tell that it used to work more than perfect (good job by the way), but in December/November I think I started with this issue. Any idea how to debug the issue?

The packages I observe some problematic are: 

* https://marketplace.visualstudio.com/items?itemName=humao.rest-client
* https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker

My workaround is to download those extensions that cause problem manually, so the syncing process can continue.

* OS Version:

Linux mint 17.3

* VSCode Version:

1.19.1

## Steps to Reproduce

1. Upload a configuration that includes the above listed extensions.
2. Download the config. in a linux mint 17.3 machine.

**Comment by nonoroazoro** [comment] 2017-12-28 02:00
Duplicate of #21

**Closed** 2017-12-28 04:33 UTC
